kind: Deployment
apiVersion: apps/v1
metadata:
  name: chinzzii
spec:
  replicas: 2
  selector: # tells the controller which pods to watch/belong to
    matchLabels:
      app: chinzzii
  template:
    metadata:
      labels:
        app: chinzzii
    spec:
      containers:
        - name: chinzzii
          image: chinzzii/pipeline-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
